name: rusty_dart
description: Rust inspired sum types for dart.
version: 0.1.5
repository: https://github.com/TheMakersPrime/rusty_dart

environment:
  sdk: ^3.0.5

dependencies:
  # dependencies

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
